spring.application.name=smart-package-backend
server.port=8080
# ==========================
# MQTT
# ==========================

app.mqtt.broker=tcp://192.168.1.102:1883
app.mqtt.client-id=smart-package-backend

app.mqtt.topic.telemetry=smart-package/+/telemetry
app.mqtt.topic.event=smart-package/+/event
app.mqtt.topic.location=smart-package/+/location-scan


# ==========================
# DATABASE
# ==========================

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_package
spring.datasource.username=smartpackage
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# ==========================
# GEOLOCATION
# ==========================

app.geolocation.enabled=${GEOLOCATION_ENABLED:false}
app.geolocation.google-api-key=${GOOGLE_GEOLOCATION_API_KEY:}
app.geolocation.timeout-seconds=10