spring.application.name=smart-package-backend
server.port=8080
# ==========================
# MQTT
# ==========================

app.mqtt.broker=tcp://192.168.1.102:1883
app.mqtt.client-id=smart-package-backend

app.mqtt.topic.telemetry=smart-package/+/telemetry
app.mqtt.topic.event=smart-package/+/event
app.mqtt.topic.location=smart-package/+/location-scan